[tox]
requires =
    tox>=4
envlist = black, ruff, mypy, py314
skipsdist = true
skip_missing_interpreters = true

[testenv]
deps = uv
commands =
    uv run pytest --basetemp={envtmpdir} -v --ff --doctest-modules tests meta_agent

[testenv:black]
deps = uv
commands =
    uv run black --check --diff --color tests meta_agent

[testenv:mypy]
deps = uv
commands =
    uv run mypy --strict meta_agent

[testenv:ruff]
deps = uv
commands =
    uv run ruff check tests meta_agent
